var n;typeof browser=="undefined"&&(browser=chrome);
const aa=navigator.userAgent.includes("OPR/"),ba=navigator.userAgent.includes("YaBrowser/"),ca=Boolean,u=Object.values,y=RegExp.prototype.test,da=RegExp.prototype.exec,ea=Array.isArray,fa=Array.from,ia=Array.prototype.includes,B=Math.floor,D=Math.random,E=Object.isExtensible,ja=Function.apply.bind(Array.prototype.push),F=Function.apply.bind(String.fromCharCode,null),ka=Function.call.bind(String.prototype.charCodeAt),la=String.fromCharCode,ma=Function.bind.bind(function(a){return this[a]}),na=Function.bind.bind(function(a){return a&&
a[this]}),oa=["date","content-type","content-length"];function pa(a){return F(a instanceof ArrayBuffer?new Uint8Array(a):a)}function ra(a){return E(a)?a.source.replaceAll("\\/","/"):a}function sa(a){return a.replace(/[a-z]/gi,function(b){return la((b=ka(b))+((b&31)>13?-13:13))})}const H={};H[-1]=[2,[111,112],[111]];H[1]=[2,[115,116,117,124,118,119,120,121,127,131,132,123,125,133,126,129,130,134,135],[115,111,112,113,114]];
H[2]=[2,[114,113,113,115,116,117,118,122,119,125,126,124,121,120,123,112],[111,112,114]];H[3]=[null,[113,114,115,116,117],[112]];H[4]=[2,[111,101,113,112,114,118,119,124,115,116,117,120,121,122,123],[111]];H[5]=[null,[111,112,113],[111]];H[6]=[null,[],[111]];
const ta={16:1,17:2,18:4,45:8,46:16},ua={http:1,https:9,ftp:2,ftps:10,idmreg:12,idmdwnlmfv3:33,idmdwnlmfv4:33,idmdwnlmfv5:33},va=y.bind(/^(?:https?|socks[45])$/),wa={direct:2,auto_detect:3,system:4,pac_script:5,fixed_servers:7},xa={"text/html":"HTML|HTM","text/css":"CSS","text/javascript":"JS|JSON","text/mspg-legacyinfo":"MSI|MSP","text/plain":"TXT|VTT|SRT|M3U|PLS|M3U8|MPD|F4M|TORRENT|BTT","text/srt":"SRT","text/vtt":"VTT|SRT","text/xml":"XML|MPD|F4M|TTML|TTML2","text/x-javascript":"JS|JSON","text/x-json":"JSON",
"application/dash+xml":"MPD","application/f4m+xml":"F4M|MPD","application/gzip":"GZ","application/javascript":"JS","application/json":"JSON","application/json+protobuf":"JSON","application/msword":"DOC|DOCX|DOT|DOTX","application/ocsp-response":"OCSP","application/octet-stream-m3u8":"M3U8","application/pdf":"PDF","application/pkix-crl":"CRL","application/torrent":"TORRENT|BTT","application/ttaf+xml":"DFXP","application/ttml+xml":"TTML|TTML2","application/vnd.apple.mpegurl":"M3U8","application/vnd.yt-ump":"UMP",
"application/zip":"ZIP","application/x-7z-compressed":"7Z","application/x-aim":"PLJ","application/x-bittorrent":"TORRENT|BTT","application/x-chrome-extension":"CRX","application/x-compress":"Z","application/x-compress-7z":"7Z","application/x-compressed":"ARJ","application/x-dosexec":"EXE","application/x-gtar":"TAR","application/x-gzip":"GZ","application/x-gzip-compressed":"GZ","application/x-javascript":"JS","application/x-mpegurl":"M3U8","application/x-msdos-program":"EXE|DLL","application/x-msi":"MSI",
"application/x-msp":"MSP","application/x-ole-storage":"MSI|MSP","application/x-rar":"RAR","application/x-rar-compressed":"RAR","application/x-sdlc":"EXE|SDLC","application/x-shockwave-flash":"SWF","application/x-silverlight-app":"XAP","application/x-subrip":"SRT","application/x-tar":"TAR","application/x-zip":"ZIP","application/x-zip-compressed":"ZIP","video/3gpp":"3GP|3GPP","video/3gpp2":"3GP|3GPP","video/avi":"AVI","video/f4f":"F4F","video/f4m":"F4M","video/flv":"FLV","video/mp2t":"TS|TSV|M3U8",
"video/mp4":"MP4|M4V|M4S","video/mpeg":"MPG|MPEG","video/mpegurl":"M3U|M3U8","video/mpg4":"MP4|M4V","video/msvideo":"AVI","video/quicktime":"MOV|QT","video/vnd.mpeg.dash.mpd":"MPD","video/webm":"WEBM","video/x-flash-video":"FLV","video/x-flv":"FLV","video/x-mp4":"MP4|M4V","video/x-mpegurl":"M3U|M3U8","video/x-mpg4":"MP4|M4V","video/x-ms-asf":"ASF","video/x-ms-wmv":"WMV","video/x-msvideo":"AVI","audio/3gpp":"3GP|3GPP","audio/3gpp2":"3GP|3GPP","audio/mp2t":"TS|TSA|M3U8","audio/mp3":"MP3","audio/mp4":"M4A|MP4|M4S",
"audio/mp4a-latm":"M4A|MP4","audio/mpeg":"MP3","audio/mpeg4-generic":"M4A|MP4","audio/mpegurl":"M3U|M3U8","audio/webm":"WEBM","audio/wav":"WAV","audio/x-mpeg":"MP3","audio/x-mpegurl":"M3U|M3U8","audio/x-ms-wma":"WMA","audio/x-wav":"WAV","ilm/tm":"MP3","image/avif":"AVIF","image/gif":"GIF|GFA","image/icon":"ICO|CUR","image/jpg":"JPG|JPEG","image/jpeg":"JPG|JPEG","image/png":"PNG|APNG","image/tiff":"TIF|TIFF","image/vnd.microsoft.icon":"ICO|CUR","image/webp":"WEBP","image/x-icon":"ICO|CUR","flv-application/octet-stream":"FLV"};
var ya,za,Aa;const J=globalThis,Ba=browser.runtime.id,K=browser.runtime.getManifest();var Ca=K.permissions.includes("notifications")||null;const Da={16:"images/logo16.png",32:"images/logo32.png"},Ea={16:"images/logo16x.png",32:"images/logo32x.png"},Fa=["127.0.0.1:1001","0.1.0.1:1001"],Ga=RegExp("(?!)"),Ha=["main_frame","sub_frame"],Ia=["object","image"];var Ja=Ia.concat("xmlhttprequest","media"),L=Ha.concat(Ia,"xmlhttprequest","media","other");
const M=["*://*/*"],Ka=["ftp://*/*"],La=M.concat(Ka,"file:///*","about:blank"),Ma=M.concat("about:blank"),Na=btoa(D().toString().substr(2,9)),Oa=browser.runtime.getURL("welcome.html?"+(Na?`auth=${Na}&`:"")),Pa=browser.runtime.getURL("").slice(0,-1),Qa=aa||ba,Ra=sa("KZYUggcErdhrfg|bcra|fraq|frgErdhrfgUrnqre|hcybnq|ybnqraq|erfcbafrGrkg|srgpu|urnqref|obql|grkg|wfba|trgErnqre|cvcrGuebhtu|Urnqref|npprcg|*/*|nccyvpngvba/iaq.g1p|Erfcbafr|hey|trg"),Sa=y.bind(/^(?:chrome|about|chrome-extension|chrome-search|ms-browser-extension|ms-appx-web|moz-extension):/),
Ta=y.bind(/^(?:application\/(?:json|x-javascript)|text\/(?:javascript|plain))$/),Ua=y.bind(/^(HTM|HTML|CGI|PHP|ASP|ASPX|JSP|JSPX)$/i),Va=y.bind(/^(MPD|M3U8|F4M)$/i),Wa=y.bind(/^ftp:|^idmreg:|\bidman|\binternetdownloadmanager\b/i),Xa=y.bind(/^[GPTSDVACRHX]*$/),Ya=da.bind(/^(.*?)(,\s*)?\bapplication\/vnd\.t1c\.(\w+)-([^\s,]+)(?:,\s*)?(.*)$/),Za=da.bind(/\.([^.\\/]*?)(?:\.[0-9.]+)?$/),$a=da.bind(/^v(\d+)\.(\d+)(?:b(\d+))?\b/),ab=ia.bind([301,302,303,307,308]),bb=/[:,;]/,cb=/[,;]/,db=[null,"debug.js",
"document.js"],eb=y.bind(RegExp("messaging host not found","i"));
function N(a,b,c,e,d,f,g,h){if(a){var k=["MSG#",a,"#",b,"#",c,"#",e];this.l=a;this.type=b;this.A=c;this.j=e;this.g=d||[];this.o=k;this.D=g;this.C=h;if(d)for(let l of d)k.push(":",l||0);if(f)for(let l in f)if(parseInt(l)&&(g=l,a=f[l],a!=null&&!this.m))switch(b=this.o,c=this.D,d=this.C,e=c&&d,d=d?"/":":",h=a instanceof String?"string":typeof a,b.push(",",g,"="),h){case "string":b.push(fb(a),":",a);break;case "number":b.push(a);break;case "boolean":b.push(a?1:0);break;case "object":if(a instanceof Array){g=
b.length;k=h=0;for(let m of a)m instanceof ArrayBuffer||m instanceof Uint8Array?(c?(m=pa(m),h+=m.length):h+=m.byteLength,++k):(m=m.toString(),h+=fb(m)),b.push(m);k&&e?(a=btoa(b.splice(g).join("")),b.push(a.length,"%",a)):b.splice(g,0,h,k?d:":")}else a instanceof ArrayBuffer||a instanceof Uint8Array?e?(a=btoa(pa(a)),b.push(a.length,"%",a)):c?(a=pa(a),b.push(a.length,":",a)):b.push(a.byteLength,d,a):a instanceof Blob&&b.push(a.size,d,a)}}else this.v=new FileReader}
function gb(){this.g=gb.prototype.B++}gb.prototype.B=1;function hb(a,b,c,e){this.id=a;this.port=b;c&&(this.h=c=c.toLowerCase(),this.i=c=="iframe");e&&(this.j=e)}hb.prototype.g=0;function O(a,b){return`${a},${b}`}function ib(a,b,c){this.id=O(b,a);this.h=c==null||c<0?null:O(b,c)}function jb(){}function kb(a,b,c){a.m?a.h(a):(b.g=c||0,b.h=0,a.v.onload=a.B.bind(a,b),lb(a,b,0,50))}
N.prototype.B=function(a){for(var b=this.v.result;;)switch(a.h){case 0:var c=b.search(bb);if(c<=0)return this.h(this);var e=b[c],d=b.slice(0,c++).split("#",6);if(d.length!=5||d[0]!="MSG")return this.h(this);this.l=parseInt(d[1]);this.type=parseInt(d[2]);this.A=parseInt(d[3]);this.j=parseInt(d[4]);b=b.slice(c);a.g+=c;a.h=e==":"?1:e==","?2:5;break;case 1:c=b.search(cb);if(c<=0)return c?lb(this,a,b.length,100):this.h(this);e=b[c];d=this.g=b.slice(0,c++).split(":");for(var f=0;f<d.length;f++){let g=d[f];
d[f]=g.includes(".")?parseFloat(g):parseInt(g)}b=b.slice(c);a.g+=c;a.h=e==","?2:5;break;case 2:c=b.search(bb);if(c<=0)return c?lb(this,a,b.length,25):this.h(this);e=b[c];f=b.slice(0,c++).split("=",3);if(f.length!=2)return this.h(this);d=parseInt(f[0]);f=parseInt(f[1]);a.g+=c;if(e==":"){a.j=d;a.i=f;a.h=3;b=a;a=a.i;c=b.g;b=b.slice(c,c+a);b.size==a?this.v.readAsText(b):this.h(this);return}this[d]=f;b=b.slice(c);a.h=e==","?2:5;break;case 3:return this[a.j]=b,a.g+=a.i,a.h=4,lb(this,a,0,21);case 4:switch(b[0]){case ",":a.h=
2;b=b.slice(1);break;case ";":a.h=5;break;default:return this.h(this)}a.g++;break;case 5:this.m=!0;this.u(this);a.size>a.g&&(b=new N,b.u=this.u,b.h=this.h,kb(b,a,a.g));return}};function lb(a,b,c,e){let d=b.g;c=d+c;b.size>c?a.v.readAsBinaryString(b.slice(d,c+e)):a.h(a)}
function Q(){let a=this.constructor.prototype;for(let b in a)b.startsWith("_")||b=="constructor"||(this[b]=a[b].bind(this));this.B=0;this.J=null;this.O=this.na=0;this.Ra=1;this.C=this.A=null;this.Qb=K.version||"";this.Ta="";this.qa=0;this.ha=!1;this.$=null;this.M=!1;this.I=this.H=null;this.Pa=this.va=!1;this.Ua=!0;this.Na=this.R=null;this.Sa=this.ga=this.ia=!1;this.hb=1;this.ya=this.v=this.N=null;this.za=1;this.Va=0;this.Ma=null;this.Oa=Ga;this.X=[];this.xa=0;this.Qa=null;this.Ba=this.pa=!1;this.D=
null;this.ra=Array(16);this.i={};this.m={};this.g={};this.u={};this.h={};this.U={};this.l={};this.j={};this.ja={};this.aa={};this.o={};this.ba={};this.ba.Sb=[];this.Ja=[];mb(this,!1);browser.action.onClicked.addListener(this.ib);browser.contextMenus.onClicked.addListener(this.jb);browser.runtime.onMessage.addListener(this.mb);browser.windows.onCreated.addListener(this.bb);browser.windows.onRemoved.addListener(this.cb);browser.windows.onFocusChanged.addListener(this.Ob);browser.windows.onBoundsChanged.addListener(this.Nb);
browser.tabs.onActivated.addListener(this.Eb);browser.tabs.onUpdated.addListener(this.Hb);browser.tabs.onAttached.addListener(this.Fb);browser.tabs.onRemoved.addListener(this.Gb);nb(this);ob(this)}n=Q.prototype;n.mb=function(a,b){switch(a[0]){case 38:a[1]&&this.ha&&browser.storage.local.set({silent:!0});browser.tabs.remove(b.tab.id);break;case 44:a=new URL(a[1]);a.search.startsWith("?d=")&&this.ma("idmreg:"+a.href.substr(a.protocol.length));break;case 43:browser.management.uninstallSelf({showConfirmDialog:!0})}};
n.jb=function(a,b){let c=a.menuItemId;if(c!=null)return pb[c][4].apply(this,arguments)};n.ib=function(a){if(this.Sa){var b=a.id,c=this.o[b];mb(this,c,b,!0);this.ga&&(c?(this.fa(a.windowId),qb(this,b)):rb(this,b))}};function mb(a,b,c,e){c?a.o[c]=!b:a.Sa=b||e;sb(b,c,e)}
function sb(a,b,c){if(c||!b||!a){var e=a?Da:Ea;browser.action.setTitle({title:a?tb+ub:b?vb+ub:c?vb:wb,tabId:b});browser.action.setIcon({path:e,tabId:b});a||browser.action.setBadgeBackgroundColor({color:"#606060"});browser.action.setBadgeText({text:a?"":"X",tabId:b})}}
function zb(a,b){browser.downloads.setUiOptions||browser.downloads.setShelfEnabled(!b);b?(a.L(3,browser.downloads.onCreated,a.kb),a.L(3,browser.downloads.onDeterminingFilename,a.lb),b=Aa?[]:["extraHeaders"],a.L(4,browser.webRequest.onBeforeRequest,a.ab,{urls:Ka,types:Ha}),a.L(4,browser.webRequest.onBeforeRequest,a.ab,{urls:M,types:L},["requestBody"]),a.L(4,browser.webRequest.onBeforeSendHeaders,a.Ib,{urls:M,types:L},["requestHeaders"].concat(b)),a.L(4,browser.webRequest.onHeadersReceived,a.Lb,{urls:M,
types:L},["responseHeaders"]),a.L(4,browser.webRequest.onResponseStarted,a.Mb,{urls:M,types:L}),a.L(4,browser.webRequest.onErrorOccurred,a.Kb,{urls:M,types:L}),a.L(4,browser.webRequest.onCompleted,a.Jb,{urls:M,types:L})):a.Ka(3,4)}
async function Ab(a,b){let c=await browser.declarativeNetRequest.getSessionRules(),e=[],d=0;if(b&&(b=a.i[17])){a={type:"redirect",redirect:{regexSubstitution:`chrome-extension://${Ba}/captured.html?register=1#\\0`}};for(let f of b.split("|"))b={regexFilter:Bb(f,3),resourceTypes:["main_frame"]},e.push({id:++d,condition:b,action:a})}(e.length||c.length)&&await browser.declarativeNetRequest.updateSessionRules({addRules:e,removeRuleIds:c.map(na("id"))})}
n.$a=function(a){browser.runtime.lastError;if(a){var b=a.value;a=wa[b.mode];var c,e;this.ra.fill(void 0);if(a==5&&(e=b.pacScript))e.data&&e.data.length>5E4?a=4:(c=e.data)?(a=6,c=c.replace(/\blet\b/g,"var").replace(/,(?=(?:\s*\/\/.*?\n)*\s*[\]}])/g,"")):c=e.url,this.ra.fill(!0);else if(a==7){b=b.rules;e=b.bypassList;c=Cb(this,b.singleProxy);if(!c){c=Cb(this,b.fallbackProxy);let d=Cb(this,b.proxyForHttp,1),f=Cb(this,b.proxyForHttps,9);b=Cb(this,b.proxyForFtp,2);d!=f||d!=b||d!=c&&c?(c=`${d??""};${f??
""};${b??""};${c??""}`,++a):c=d}e&&e.length&&(c+=";"+e.join(","))}b=a<5?a.toString():c?`${a}:${c}`:null;b!=this.D&&(this.D=b)}};function Cb(a,b,c){if(b){let e=b.scheme||"http",d=e=="https";a=a.ra;c?a[c]=d:a.fill(d);if(va(e))return`${e}://${b.host}${b.port?":":""}${b.port||""}`}}n.wa=function(a,b,c,e){let d=this.l;return b in d?d[b]:d[b]=new hb(b,a,c,e)};
function Db(a,b,c,e,d){let f,g,h;E(b)?(f=b.frameId??0,g=b.parentFrameId,h=b.method&&b.id,c||=b.tabId,d||=b.url):f=b;let k=a.u[O(c,f)];k||(k=new ib(f,c,g),a.u[k.id]=k);h?(k.l!=h&&(k.l=h,k.v=d,k.j=!1,k.g&&(k.g=d.startsWith(b.initiator||b.originUrl))),k.A=b.method=="POST"):d&&(d.startsWith("about:blank")?f&&(k.g=!0):k.G=d);e!=null&&(k.o=e);return k}function Eb(a){let b=new gb;return a.U[b.g]=b}function Fb(a,b){let c;b instanceof gb?c=b.g:b=a.U[c=b];delete a.U[c];return b}
function Gb(a,b){for(let c of a.X)if(c&&c[101].test(b))return c.W;return 0}
n.Aa=function(){var a=this.na%(Fa.length+1);a<Fa.length?(a=this.J=new WebSocket(`ws://${Fa[a]}/?cid=${this.$||0}&rnd=${D().toString().substr(2,9)}`,"plugin.v3.internetdownloadmanager.com"),a.onerror=Hb,a.onopen=this.Ha,a.onclose=this.la,a.onmessage=this.Db,a.readyState==1?this.Ha(1):a.readyState==3?this.la():this.A=J.setTimeout(this.la,1500,a)):(a=this.J=browser.runtime.connectNative("com.tonec.idm"),a.onDisconnect.addListener(this.la),a.onMessage.addListener(this.rb),this.A=J.setTimeout(this.Ha,
0,2))};n.Ha=function(a){this.A&&(J.clearTimeout(this.A),this.A=null);this.B=E(a)?1:a;this.Ra=1;this.ha=!1;a=browser.i18n.getUILanguage().replace("_","-");a=="sr"&&(a+="-Cyrl-CS");R(this,2,5,Qa?0:1024,[112,87,Qa?1028:1031,0,16845059,this.$,15,K.manifest_version],{[112]:za,[113]:ya,[116]:a})};
n.la=function(a){this.A&&(J.clearTimeout(this.A),this.A=null);this.C&&(J.clearTimeout(this.C),this.C=null);var b=browser.runtime.lastError||a&&a.error,c=this.J;if(c instanceof WebSocket){if(a===c)return c.close()}else c&&eb(b&&b.message)&&(this.ha=!0);this.J=null;this.B&&(this.B=0,this.ja={},zb(this,!1),Ab(this,!1),this.Ka(1,2),this.ga=!1,this.D=this.Ma=null,mb(this,!1));a=++this.na;b=Fa.length+1;c=a/b;c<120&&(c==1&&Ib(this),!a||a%b?this.Aa():J.setTimeout(this.Aa,5E3*c))};
n.Xa=function(){let a=this.J;a instanceof WebSocket?a.close():a&&(a.disconnect(),this.la())};n.Ga=function(a){if(this.C)a?(this.C=null,R(this,0,1,1)):J.clearTimeout(this.C);else if(a)return;this.C=J.setTimeout(this.Ga,15E3,!0)};n.Db=function(a){let b=new N;b.u=this.Ya;b.h=this.Xa;kb(b,a.data)};n.rb=function(a){let b=new N;b.u=this.Ya;b.h=this.Xa;kb(b,new Blob([a]))};
function R(a,b,c,e,d,f){let g=a.O;var h=a.B;if(!h)return 0;let k=a.Ra++;b=new N(k,b,c,e,d,f,h==2,g>=99);if(h==1){h=a.J;var l=h.send;b.m||(b.o.push(";"),b.m=!0);l.call(h,new Blob(b.o))}else try{l=a.J;var m=l.postMessage;b.m||(b.o.push(";"),b.m=!0);m.call(l,b.o.join(""))}catch(p){return a.la(),0}e&1&&(a.ja[k]=b);a.C&&a.Ga();return k}
function Jb(a,b){if(b.g){var c=b.g[1],e=a.j[c];if(e)return e.g?b.i=e.port.id:null;e=a.m;for(var d in e)if(e[d].l==c)return b.i=d}c=b[6];d=b[17];e=b[50];let f=b[7];var g=a.ba;let h=a.l;a=a.g;let k,l,m;if((k=g[c])||(k=g[d]))return b.i=k.id;if(k=g[e])m=k.id;for(let p in h){g=h[p];let q=g.j;if(q){if(q==c||q==d||q==e){k=g.port;if(f){let t=a[k.tabId];t&&t.G!=f&&(k=null)}if(k)return b.i=k.id}q==f&&(l=g.port.id)}}return m?b.i=m:l?b.i=l:null}
function Kb(a,b){let c=b.i;if(c)return c;if(b.g){var e=a.g[O(b.g[6],b.g[7])];e?c=e.id:(e=b.g[7])&&a.m[e]&&(c=e)}if(c||=Jb(a,b))return b.i=c;e=a.m;let d=b[50],f=b[7];for(let g in e){let h=e[g];if(h.G==d)return b.i=h.id;h.G==f&&(c=h.id)}return c?b.i=c:f?browser.tabs.query({url:f}).then(g=>g?.length&&(g=a.g[g[0].id])?b.i=g.id:null,()=>null):null}
async function Lb(a,b){var c=b.tabId;let e=b.ca;if(e>0&&!b.i){var d=await browser.webNavigation.getFrame({frameId:e,tabId:c});d&&(d=d.parentFrameId,d>=0&&(b.i=O(c,d)))}if(e!=null&&b.o){if(d=a.u[O(c,e)]){b.l=d.l;b.u|=d.j;b.j|=d.o;b.B=d.g;let f=d.da;f&&b.G!=f&&(b.da=f);b.i||(b.i=d.h);(d=a.j[b.l])&&!d.port&&(d.port=b)}a.g[O(c,e)]=b;d=b.W;c=[11,a.O,b.id,c,e,d,b.j,b.u,a.i[22],a.i[23],db[a.Pa?1:null]];d&&b.u&&(a=a.X[d],c.push(a.Tb,db[a.gb]),ja(c,a.eb.map(ma(a)).map(ra)));b.postMessage(c)}}
n.ma=async function(a,b,c,e,d,f){var g=S(a);if(g){var h=(g&32)>0,k=(g&=7)==1,l;k&&!h&&(l=await T(a));g=[g];a={[6]:Mb(a,k&&this.M),[50]:b,[7]:c,[8]:e,[100]:d,[102]:f,[51]:U(l),[54]:navigator.userAgent,[121]:this.D};R(this,14,1,0,g,a)}};
async function Nb(a,b,c){if(b&&b.length){var e=b.map(k=>T(k[0]));if(c){var d=c.i;var f=c.O;var g=c.u;d&&!f&&e.push(T(d))}e.length&&(e=await Promise.all(e),b.forEach(k=>k[5]=U(e.shift())),e.length&&(f=U(e.shift())));c=0;var h=[0,0,0];d={[8]:4,[54]:navigator.userAgent,[7]:d,[110]:g,[111]:f,[121]:a.D};b.length>1&&(h[1]=R(a,15,1,0,[b.length],d),c=16,d={});for(let k of b)h[2]++,d[6]=k[0],d[100]=k[2],d[102]=k[3],d[50]=k[4],d[51]=k[5],R(a,14,2,c,h,d)}}
n.Da=function(a,b){if(!this.B)return Ob(b.id,"cannot_contact_idm");let c=a.linkUrl,e=a.pageUrl,d=e,f=this.g[O(b.id,a.frameId)];if(a.menuItemId==5)return browser.downloads.search({query:[c]},this.fb.bind(this,c));if(a.menuItemId==2){if(c=a.frameUrl,c&&c!="about:blank"||(c=e,d=null),this.H&&f?.W)return Pb(this,!0)}else if(!c){c=a.srcUrl;if(!S(c)){if(this.H&&f?.W&&a.mediaType=="video")return Pb(this,!0);return}if(f&&c)return a=Eb(this),a.tabId=b.id,a.port=f,a.o=c,a.v=d,a.i=e,a.m=4,f.postMessage([18,
a.g,c])}this.ma(c,d,e,4)};n.La=function(a,b){if(!this.B)return Ob(b.id,"cannot_contact_idm");Qb(this,b.id,a.menuItemId==3)};n.fb=function(a,b){let c,e,d;for(;c=b.pop();)c.exists&&c.state=="complete"?e||(d||=c.referrer):(e||=c.referrer,browser.downloads.erase({id:c.id}));this.ma(a,e||d,null,4)};
function Qb(a,b,c,e,d,f,g,h,k){if(!e||a.i[-5]){var l=a.g[b];if(l){var m=Eb(a);m.tabId=b;m.port=l;m.N=c;m.U=d;m.h=0;m.j=[];if(l=e&&!!f)m.J=!0,m.M=f,m.C=g,m.D=h,m.A=k,f.h||Rb(a,f);f=m.g;(e=e&&a.i[12])?(e=e.replace(/\./g,"\\.").replace(/\*/g,".*").replace(/~/g,"(?:.*\\.)?"),e=`${"^(?:http|https|ftp|ftps)://"}(?:[^\\/]*@)?(?:${e})(?::\\d+)?(?:\\W|$)`):e="^(?:http|https|ftp|ftps)://";m.l=Sb(a,b,[12,f,c,l||d,e]);m.H=0;m.l||Fb(a,m)}}}
n.Rb=function(a,b,c,e,d,f,g,h){if(a=this.U[b]){e&&(a.h+=e);g&&(a.i=g);h&&(a.u=h);if(d&&(typeof d=="string"&&(d=JSON.parse(d)),d instanceof Array)){if(f)for(let k of d)k[4]=f;ja(a.j,d)}++a.H<a.l||(a.J?(e=a.tabId,(d=this.h[a.port.g])&&d.K==e&&a.h&&(f=a.A,g=d.h,h=d.i,R(this,10,1,0,[4294967295,d.A,Math.round(a.C*f+(d.l+g)*h),Math.round(a.D*f+(d.I+g)*h),0,a.h]),this.v=e,Sb(this,e,[13,!0]))):(e=a.j,e.length?Nb(this,e,a):Ob(a.tabId,"cannot_find_links")),Fb(this,a))}};
n.wb=function(a,b,c,e){(a=Fb(this,b))&&this.ma(a.o,a.v,a.i,a.m,c,e)};n.kb=function(a){if(!this.Ba&&this.i[-6]){var b=a.finalUrl||a.url;if(S(b,!0)){var c=a.id,e=Date.parse(a.startTime),d;for(d of u(this.j))if(b==d.url&&e>=d.$&&e-d.$<50)break;if(d&&(d.Ca=c,a.request=d,this.o[d.tabId]))return;this.aa[c]=a;browser.downloads.pause(c,Hb)}}};
n.lb=function(a,b){var c=a.id;let e=this.aa;var d=e[c];if(d){var f=this.i,g=d.request;d=a.finalUrl||(a.finalUrl=a.url);var h=g?g.ua:new URL(d),k=g?g.V:a.V=S(d,!0),l=g?g.ka:a.ka=V(a.filename||h.pathname);if(!((g?g.pa:a.l=this.pa)||this.va||f[1].test(l)&&!f[9].test(h.hostname)&&!f[19].test(h.href)))return Tb(this,c);a.request=g;a.Ub=b;e[c]=a;if(g)return W(this,2,g,a)?a.Ea=!0:Tb(this,c);if(k==1){if(!a.referrer){b=this.h;for(var m of u(this.m))if(m.G==d&&(a.referrer=m.D,(c=b[m.g])&&c.K==m.tabId))break}m=
T(d);d=d==a.url?null:T(a.url);Promise.all([m,d]).then(p=>Ub(this,a,...p));return a.Ea=!0}return Ub(this,a)}};function Ub(a,b,c,e){var d=Date.parse(b.startTime)||Date.now();d=[b.id,0,B(d),0,b.V,2];c={[6]:Mb(b.finalUrl,a.M),[4]:b.ka,[103]:b.totalBytes||null,[100]:b.filename||null,[127]:b.mime||null,[8]:b.l?2048:0,[50]:b.referrer||null,[51]:U(c),[54]:navigator.userAgent,[122]:a.D};b.finalUrl!=b.url&&(c[17]=Mb(b.url),c[56]=U(e));return!!R(a,13,1,129,d,c)||Tb(a,b.id)}
function Tb(a,b,c){let e=a.aa[b];if(e){delete a.aa[b];let d=e.request;d&&(d.Ca=null,d.Fa&&a.P(d));if(c)return browser.downloads.cancel(b,Hb),!0;e.Ea&&(e.Ea=!1,e.Ub());browser.downloads.resume(b,Hb)}}n.zb=function(a,b,c,e,d,f){this.wa(a,b,c,e);R(this,23,2,0,[b,a.tabId,a.l,a.W,a.ca],{[132]:e,[133]:d,[134]:f})};
n.Y=function(a,b,c){if(a==4294967295)this.v=null,c=!0;else{let e=this.l[a];if(e){c=e.g;if(!c)return;if(b)switch(c){case 3:return;case 2:break;default:e.g=3;J.setTimeout(this.Y,1E3,a,!1,!0);return}e.g=0;c=!0}}c&&R(this,8,1,32,[a])};
n.Yb=async function(a,b,c,e,d,f,g,h,k,l){let m=a.tabId,p=a.g;var q=this.h[p];let t=this.o[m];if(b){var r=Fb(this,b);if(r=r&&r.I){if(!c&&a.B){let P=this.g[a.i];if(P)return P.postMessage([15,b,null,r[6],r[17],r[50],r[31],r[133],r[134]])}var v;b={};if(!e){if(!c||d==null){if(!a.h){c=a.oa;f="iframe";g=a.G;var z=!!c}if(!z){c=m;f=g=null;var x=!0}}a=this.wa(a,c,f,g);q=m==q.K&&!q.S&&(x||z||d)&&!t;!q||x||a.g||J.setTimeout(this.fa,3E3,p);var C=2;a.g=q?1:2;var G=(q?128:64)|(x?512:0);!h&&(v=this.g[m])&&(h=v.C)}h&&
(b[101]=h,b[128]=k);l&&(b[137]=l);await X(this,r,C||1,G||0,p,m,c,b);!C||x||t||Vb(this,c,d)}}else e?(this.Y(c,!0),delete this.l[c]):m!=q.K||q.S||t||(d?Vb(this,c,d,!0):Wb(this,c))};function Xb(a,b){let c=a.h[b];if(c&&c.g){var e=c.h,d=c.i;R(a,7,2,c.S?128:c.B?256:c.j?512:0,[b,Math.round((c.l+e)*d),Math.round((c.I+e)*d),Math.round((c.width-e-c.C)*d),Math.round((c.height-e)*d)])}}
function Vb(a,b,c,e){let d=a.l[b];if(d&&d.g){var f=d.port;let g,h=256;d.g==2&&(e==null&&(g=a.h[f.g])&&(e=f.tabId==g.K&&!g.S),e?(h|=128,d.g=1):h|=64);(e=d.i)&&!c&&(c=f.m);let k,l,m,p,q,t;if(c){k=c[0];l=c[1];m=c[2]||k+1;p=c[3]||l+1;q=c[4];if(c=!e&&f.m)k+=c[0],l+=c[1],m=Math.min(m+c[0],c[2]),p=Math.min(p+c[1],c[3]);if(f=a.g[f.tabId])t=f.M}R(a,9,1,h,[b,k,l,m,p,q,t])}}
n.fa=function(a){var b=this.o;let c=this.g;var e=this.h;let d=a?[e[a]]:u(e);a=[];e={};for(var f of d)!f||f.S||f.ea||b[f.K]||a.push(f.K);if(a.length)for(let g of u(this.l))g.g&&(b=g.port,f=b.tabId,a.includes(f)&&((f=b.h?b:c[f])&&f.update&&(f.update=!1,f.postMessage([14,!1])),g.h?b.h?b.postMessage([15,null,g.id]):Rb(this,b,null,e):Vb(this,g.id,null,!0)))};function Yb(a,b){let c=a.h,e;if(b=b==null?u(c):(e=c[b])?[e]:null)for(e of b)rb(a,e.K)}
function rb(a,b,c,e){e=e!=0;let d=c?0:2;c=c?32:64;for(let f of u(a.l))f.g&&f.port.tabId==b&&f.g!=d&&(e||f.h)&&(f.g=d,R(a,8,1,c,[f.id]))}function Wb(a,b){let c=a.l[b];c&&c.g==1&&(c.g=2,R(a,8,1,64,[b]))}function Zb(a,b,c,e){var d=a.xa;let f=(d&b)!=((c?255:128)&b);a.xa=c?d|=b:d&=~b;f&&(c=a.i[-32],b=a.i[-33],c=a.pa=c!=0&&(d&c)==c,d=a.Ba=b!=0&&(d&b)==b,a.Qa=(c||d)&&e||null)}
n.Ia=function(a,b,c,e,d){let f=this.h[a];if(f)if(f.ea?e&&(J.clearTimeout(f.ea),f.ea=null):e||=-1,e>=0)f.o|=b,f.u|=c,e&&(f.ea=J.setTimeout(this.Ia,e,a));else{b|=f.o;c|=f.u;f.o=f.u=f.ea=null;if(b){for(let g of u(this.m))g.h&&g.g==a&&(g.update=!0);d?this.Z(d):browser.windows.get(a,this.Z);browser.tabs.query({windowId:a,active:!0},this.Z)}if(c){if((a=this.h[a])&&!a.S&&!a.ea&&(a=a.K,!this.o[a])){b=this.l;for(let g in b)c=b[g],c.g&&c.port.tabId==a&&c.g==1&&R(this,8,1,1152,[g])}}else this.fa(a)}};
n.Z=function(a,b){browser.runtime.lastError;a instanceof Array&&(a=a.shift());if(a){var c=a.windowId||a.id,e=this.h[c];if(e){var d=!a.windowId;if(d){b&&(e.i=this.za);var f=e.j=a.state=="minimized",g=e.B=a.state=="maximized";f||(e.width=a.width,e.height=a.height,e.m=a.left,e.v=a.top,f=e.S,a=e.S=a.state=="fullscreen",g=g&&-e.m,g>0&&g<=16&&g==-e.v&&(e.h=g),a==f||b||(a?Yb(this,c):this.fa(c)))}else a.active&&(e.K=a.id),a.width&&(e.H=a.width),a.height&&(e.D=a.height);if(!e.j){a=e.width;let h=e.H;g=e.height;
f=e.D;let k=h>a||f>g;if(k||!h||!f){d||k&&browser.windows.get(c,this.Z);return}d=a-h;a=d/2;a>=0&&a<=16?(e.h=a,e.l=e.C=0):(a=e.h,aa?e.l=d-a*2:e.C=d-a*2);d=g-f-a*2;d>=(e.J?20:40)&&d<=150&&(e.I=d)}b||Xb(this,c);return e}}};function qb(a,b){return a.o[b]?!0:(a=a.g[b])&&a.j?(a.j=!1,browser.tabs.reload(b),!0):!1}n.Vb=function(a,b,c,e){a.G=b;a.D=c;a.j&&!e&&(a.j=!1);a.ca==null&&Lb(this,a);this.fa(a.g);this.H>0&&a.h&&a.W==1&&(this.i[11]?.test((new URL(b)).hostname)||Pb(this))};
n.Xb=function(a,b,c,e,d){a.C=b;a.M=d;a=[a.l,a.tabId,a.g,e,d];e={};e[110]=b;e[128]=c;R(this,21,1,0,a,e)};
n.Zb=function(a,b,c,e,d){let f=a.tabId,g=this.g[O(f,c)];if(g){var h=g.m;g.oa=e;if(g.m=d){var k=a.m;k&&(d[0]+=k[0],d[1]+=k[1],d[2]=Math.min(d[2]+k[0],k[2]),d[3]=Math.min(d[3]+k[1],k[3]));if(h&&h.join()!=d.join()){h=this.g;a=O(a.tabId,"");c=a+c;for(let l in h)l.startsWith(a)&&(k=h[l],k.i==c&&g.postMessage([16,b,k.ca,k.oa]))}}if(!this.o[f]){Vb(this,e,d);for(let l of u(this.l))l.port==g&&l.g&&l.h&&!l.i&&g.postMessage([15,null,l.id])}}};
function Rb(a,b,c,e){var d=a.g;c=[16,c];a=[b];for(let f;f=d[b.i];b=f){if(e)if(e[b.id])break;else e[b.id]=!0;a.push(f)}for(e=a.pop();b=a.pop();e=b)d=b.oa,c[2]=b.ca,c[3]=d,c[4]=d?null:b.G,c[5]=d?null:b.da,e.postMessage(c)}function Sb(a,b,c){a=a.g;b=O(b,"");let e=0;for(let d in a)d.startsWith(b)&&(a[d].postMessage(c),e++);return e}
n.sa=function(a,b){let c={},e={files:["content.js"],target:c,injectImmediately:!0};b?c.frameIds=[b]:c.allFrames=!0;if(a instanceof Array)for(;b=a.shift();)b.discarded||(c.tabId=b.id,browser.scripting.executeScript(e).catch(()=>null));else if(b=a)c.tabId=b.id||b,browser.scripting.executeScript(e).catch(()=>null)};function $b(a,b,c,e){c==null&&(c=b.A==a.N);R(a,6,2,17|(c?2048:1024)|(b.B?256:b.j?512:0),[b.A,b.g,b.width,b.height,b.m,b.v,b.i],{[117]:e})}
async function ob(a){var b=browser.windows.getAll({windowTypes:["normal","popup","app"]}),c=browser.tabs.query({active:!0});[b,c]=await Promise.all([b,c]);let e={};if(c)for(let d of c)e[d.windowId]=d;for(let d of b)b=e[d.id],c=a.Z(d,!0)||a.bb(d,!0,b),$b(a,c,d.focused,d.title||b&&b.title)}async function ac(a){await bc("system.display")&&(a.Va=(await browser.system.display.getInfo(null))[0].displayZoomFactor)}
n.Ab=function(a){let b=a.sender.tab;if(b&&!(b.id<0)){a.name=a.name.split(":").shift();var c=a.id;c==null&&(c=a.id=this.hb++);var e=b.id,d=a.name=="top";a.tabId=e;a.g=b.index<0?null:b.windowId;a.o=!0;a.A=!1;a.update=d;a.h=d;a.ca=d?0:a.sender.frameId;a.N=0;a.G=a.sender.url||d&&b.url||null;a.da=null;this.m[c]=a;d&&(this.g[e]=a);a.G&&(a.W=Gb(this,(new URL(a.G)).hostname));a.onMessage.addListener(this.Bb.bind(this,a));a.onDisconnect.addListener(this.ta);Lb(this,a)}};
n.ta=function(a){browser.runtime.lastError;if(a.o){a.o=!1;var b=O(a.tabId,a.ca),c=this.U,e=this.l,d,f=this.ba,g=this.j,h;for(let k in c)c[k].port===a&&delete c[k];for(let k in e)if(d=e[k],d.port===a)this.Y(k),delete e[k];for(let k in f)f[k]===a&&delete f[k];for(let k in g)(h=g[k],h.port!==a||h.j)||delete g[k];this.Qa===a&&Zb(this,255,!1);delete this.m[a.id];delete this.g[b];a.h&&delete this.g[a.tabId];a=this.u;for(let k in a)b==a[k].h&&delete a[k]}};
n.Bb=function(a,b){let c=b.shift();b.unshift(a);switch(c){case 21:this.Vb.apply(this,b);break;case 24:this.Xb.apply(this,b);break;case 22:this.Zb.apply(this,b);break;case 23:this.Yb.apply(this,b);break;case 41:this.zb.apply(this,b);break;case 25:this.wa.apply(this,b);break;case 26:Qb(this,a.tabId,!0,!0,!1,a,b[1],b[2],b[3]);break;case 27:this.Rb.apply(this,b);break;case 28:this.Y(4294967295);break;case 29:this.Wa.apply(this,b);break;case 30:this.Wa.apply(this,b);break;case 31:this.tb.apply(this,b);
break;case 32:this.xb.apply(this,b);break;case 39:this.ub.apply(this,b);break;case 33:this.ob.apply(this,b);break;case 34:this.sb.apply(this,b);break;case 35:this.wb.apply(this,b);break;case 36:this.Pb.apply(this,b);break;case 37:this.Cb.apply(this,b);break;case 45:this.nb.apply(this,b);break;case 46:this.qb.apply(this,b)}};
n.Ya=function(a){let b=a.type;var c=a.A,e=a.j,d=a.g,f;if(b==1){let m=d[0];if(f=this.ja[m])b=f.type,delete this.ja[m]}switch(b){case 3:this.na>=0&&(this.na=-1);var g=d[0],h=d[5],k=d[6],l=d[4];d=d[8];this.O=g;cc(this,k);dc(this,h,a);ec(this);if(l||d)d=(l?l/96:1)*(d?d/100:1),this.za=d<1.245?1:d,ob(this),this.Va&&ac(this);g<97&&this.Ga();Ib(this);break;case 4:g=this.i;(h=!!(d[3]&134217728))&&(J.idm=this);this.Pa=h;this.va=!!(d[3]&2147483648);dc(this,d[2],a);ec(this);g[-6]=(e&64)>0;g[-10]=(e&1024)>0||
Qa;g[-5]=(e&32)>0;g[-1]=(e&2)>0;g[-8]=(e&256)>0||c<2;g[-9]=(e&512)>0||c<2;g[-32]=d[0];g[-33]=d[1];g[12]=a[12];g[17]=a[17];g[23]=a[23];this.O<109?g[23]=Ra:this.O<110&&(g[23]+=sa("|Erfcbafr|hey|trg"));Y(g,a,1);Y(g,a,2);Y(g,a,3);Y(g,a,4);Y(g,a,10);Y(g,a,9,2);Y(g,a,11,2);Y(g,a,20);Y(g,a,21,1);fc(g,a,19);fc(g,a,18,1,1);a=this.i;browser.contextMenus.removeAll();for(d=1;d<pb.length;d++)g=pb[d],g[0]&&a[g[1]]&&browser.contextMenus.create({id:d.toString(),title:hc(g[2]),contexts:g[3].split(","),documentUrlPatterns:g[5]||
La,enabled:!0});this.ga||(this.ga=!0,mb(this,!0),this.L(1,browser.runtime.onConnect,this.Ab),this.L(1,browser.proxy.settings.onChange,this.$a),browser.proxy.settings.get({},this.$a),this.L(1,browser.webNavigation.onCreatedNavigationTarget,this.yb),this.L(1,browser.webNavigation.onCommitted,this.Za),this.L(1,browser.webNavigation.onHistoryStateUpdated,this.pb),Ab(this,!0),zb(this,!0),browser.tabs.query({url:M},this.sa));break;case 18:f=d[0];d=d[1];e=H[d?-d:f];if(!e)break;d=this.X[f]={};c=e[2];d.W=
f;d.Tb=f==1?sa("lbhghor"):null;d.gb=e[0];d.eb=e[1];for(g in a)(g=parseInt(g))&&(g==102||g>110&&g<150)&&(d[g]=c.includes(g)?RegExp(a[g]):a[g]);for(h of c)(k=d)[l=h]||(k[l]=Ga);g=this.X.map(na(102)).filter(ca);this.Oa=RegExp("^https?://(?:"+g.join("|")+")","i");Y(d,a,101,2);break;case 5:ic(this,d[0],e,d[1]);break;case 6:if(e&4)break;ic(this,f.g[0],e,d[2],d[1]);break;case 8:a=d[0];d=e&32;if(a==4294967295)Sb(this,this.v,[13,!1]),this.v=null;else if(a=this.l[a])a.g=d?0:2;break;case 11:d[0]==4294967295&&
(Qb(this,this.v,!0,!0),this.v=null);break;case 12:try{let m=a.g[5];d=m==4?2:3;if(m==1||m==2){if(Jb(this,a)){let p=a[4];if(this.i[3].test(p))m==1?d=6:m=4;else if(this.i[-1]||this.i[4].test(p))d=6;a[8]|=256}if(d==3){let p=this.h[this.N];p&&this.o[p.K]&&(d=1)}}if(m!=4)X(this,a,d);else{switch(a.g[4]){case 1:a[7]||(a[7]=a[50]);break;case 3:a[7]||(a[7]=a[32]),a[50]||(a[50]=a[31])}jc(this,a)}}catch(m){X(this,a,0)}break;case 13:a=f.g[0];g=f.g[5];d=d[1];h=d==3;if(g<=3)f.j&128?Tb(this,a,h):this.P(a,h);else if(g==
5)if(d){if(f=(l=this.j[a])&&l.m)d=l.url,g=l.method,h=l.requestHeaders,(k=l.i)&&((k=kc(k,h,!0))??(g="GET")),l.port.postMessage([19,a,f,d,g,h,k])}else lc(this,a);break;case 20:d=!a[123];a=[a.l];g={};g[121]=this.D;R(this,1,2,d?2:4,a,g);break;case 24:mc(this,a);break;case 22:nc(d[0],d[1],a[131],a[130]);break;case 100:e&1&&R(this,100,1,0,[a.l],a);break;default:e&1&&R(this,1,2,0,[a.l])}};
async function nc(a,b,c,e){Ca==null&&(Ca=await bc("notifications")||!1);Ca&&(browser.notifications.create(a.toString(),{type:"basic",title:e??"",message:c,iconUrl:"images/logo48.png"}),b&&J.setTimeout(browser.notifications.clear,b*1E3,a.toString()))}async function mc(a,b){let c=await T(b[6],!!(b.j&16));b=[b.l,c?c.length:0];let e={[51]:U(c)};R(a,1,2,c?2:4,b,e)}
async function jc(a,b){try{let g,h=b.i||b.g[2],k=b.g[8],l=a.l[k];if(l&&l.port)g=l.port;else if(h in a.m)g=a.m[h];else if(h=await Kb(a,b))g=a.m[h];else{let m=await browser.windows.getLastFocused();if(m){let p=a.h[m.id];p&&(g=a.g[p.K])}}if(g){b.i=g.id;var c=a.h[g.g];if(c&&c.g){var e=a.g[g.tabId];e&&e.update&&(e.update=!1,e.postMessage([14,!0]));var d=Eb(a),f=[15,d.g,k];d.I=b;k||f.push(b[6],b[17],b[50],b[31],b[133],b[134]);g.h||Rb(a,g,d.g);g.postMessage(f)}else X(a,b,1)}else X(a,b,0)}catch(g){X(a,b,
0)}}async function X(a,b,c,e,d,f,g,h){c!=-1&&(e|=c==0?4:2,h||={},h[8]=b[8],d=[b.l,c,d,g,f,-1],b.j&32&&(c==3||c==2)&&(b=await T(b[6],!!(b.j&16)))&&(d[5]=b.length,h[51]=U(b)),R(a,1,2,e,d,h))}n.yb=function(a){Db(this,a).i=!0};
n.Za=function(a,b){var c=a.tabId,e=a.frameId;let d=a.url;var f=a.transitionType,g=a.frameType,h=a.documentId;let k=a.documentLifecycle=="prerender";this.R!=c||Sa(d)||(this.R=null);e&&k&&g=="outermost_frame"&&(e=a.frameId=0);f=f&&f.endsWith("_subframe");var l=!0;if(g=this.u[O(c,e)]){l=g.m;g.m=k?h:null;if(l&&l==h)return;h=g.u;l=!(d&&h&&(new URL(d)).hostname==(new URL(h)).hostname);g.u=d}else k&&(g=Db(this,a),g.m=h);!f&&this.o[c]&&mb(this,l,c);if(h=this.g[O(c,e)])if(this.v&&(a=this.h[h.g])&&a.K==this.v&&
this.Y(4294967295),b){a:{b=h.G;c=new URL(b);e=new URL(d);if(c.origin==e.origin&&c.pathname==e.pathname)switch(Gb(this,c.hostname)){case 1:if(c.pathname=="/watch"&&c.searchParams.get("v")==e.searchParams.get("v")){b=!0;break a}break;case 4:if((c.pathname.startsWith("/p/")||c.pathname.startsWith("/reel/"))&&c.searchParams.get("img_index")==e.searchParams.get("img_index")){b=!0;break a}}b=d==b}if(!b){b=this.l;var m;for(let p in b)if(m=b[p],m.port===h)h.W==2||h.W==4?Wb(this,p):(this.Y(p),delete b[p]);
h.N++;h.G=d;h.h&&(h.update=!0);h.postMessage([17,!0])}}else this.ta(h,!0),f&&h.G=="about:blank"&&this.sa(c,e);else f&&d=="about:blank"?(Db(this,a),this.sa(c,e)):g&&g.i&&(g.G||!b)&&(g.i=!1)};n.pb=function(a){return this.Za(a,!0)};
n.bb=function(a,b,c){let e=a.id;c={A:e,width:a.width,height:a.height,m:a.left,v:a.top,i:this.za,h:8,I:66,l:0,C:0,J:a.type=="popup"||a.type=="app",S:a.state=="fullscreen",B:a.state=="maximized",j:a.state=="minimized",K:c&&c.id,D:c&&c.height,H:c&&c.width,g:null,ea:null};Object.setPrototypeOf(c,jb.prototype);this.h[e]=c;a.focused&&(this.N=e);b&&(browser.tabs.query({windowId:e,active:!0},this.Z),browser.tabs.query({windowId:e,url:M},this.Wb),browser.tabs.query({windowId:e,url:M},this.sa));return c};
n.Wb=function(a){for(let b of a)Db(this,0,b.id,!0,b.url)};n.cb=function(a){R(this,5,1,32,[a]);delete this.h[a]};n.Ob=function(a){if(a>0){let b=this.h[a];b&&(this.N=a,b.g||$b(this,b,!0),browser.windows.onBoundsChanged||browser.windows.get(a,this.Z),qb(this,b.K))}else this.N=null};n.Nb=function(a){this.Ia(a.id,!0,!1,-1,a)};function ic(a,b,c,e,d){let f=a.h[b];f?(e&&(f.i=e),d&&(f.g=d),e=!!(c&128),f.S!=e&&(f.S=e)&&Yb(a,b),(d||c&4096)&&Xb(a,b)):a.cb(b)}
n.Hb=function(a,b,c){let e=c.active;c=c.windowId;let d=e&&this.h[c];d&&(d.g||$b(this,d));b.status=="complete"&&(a=this.g[a])&&!a.A&&(a.A=!0,e&&this.fa(c))};n.Gb=function(a){let b=this.g,c=this.u,e=O(a,"");this.R==a&&(this.R=null);let d=b[a];d&&this.ta(d,!0);for(let f in b)f.startsWith(e)&&this.ta(b[f],!0);for(let f in c)f.startsWith(e)&&delete c[f];delete this.o[a]};
n.Eb=function(a){let b=a.tabId;a=a.windowId;this.xa=0;this.v&&this.Y(4294967295);var c=this.h[a];c&&(rb(this,c.K),c.K=b,(c=this.R)&&b!=c&&this.B&&(this.R=null,J.setTimeout(browser.tabs.remove,250,c)),browser.tabs.get(b,this.Z),qb(this,b)||this.fa(a))};n.Fb=function(a,b){b=b.newWindowId;for(let c of u(this.m))c.tabId==a&&(c.g=b);rb(this,a,!0)};
n.Wa=function(a,b,c){if(a.h){let e=a.tabId;a=a.g;let d=this.h[a];this.v&&this.Y(4294967295);if(d&&d.K==e){let f=!1;b&&(d.H=b,f=!0);c&&(d.D=c,f=!0);rb(this,e,!1,f);this.Ia(a,f,!1,500)}}else a.oa&&(b=this.g[a.i])&&b.postMessage([16,null,a.ca,a.oa])};n.tb=function(a,b,c){(b=ta[b])&&Zb(this,b,c,a)};n.xb=function(a,b,c){b==0&&Zb(this,128,c,a)};n.ub=function(a,b,c,e){this.ya=a.id;a.I=b;a.H=c;a.J=e};n.ob=function(){Zb(this,255,!1)};
n.sb=function(a,b,c,e){var d=a.l;d&&(a=32,d=[d,c==null?(a|=16,-2):c],R(this,16,1,a,d,{[110]:b,[115]:e}))};n.Pb=function(a,b,c){if(a=this.j[b])R(this,16,1,48,[a.id,0],{[115]:c}),a.ba=!1,a.Fa&&this.P(a)};n.qb=function(a,b,c,e){b!=null&&(a.O=b?1:-1);c!=null&&(a.v=c?1:e?2:-1)};n.Cb=function(a,b,c,e){R(this,19,2,0,[b,c,a.tabId,a.l],e)};
n.nb=function(a,b,c){if(a=this.j[b]){if(a.m<0&&c!=null){a=new Uint8Array(c.length);for(let e=0;e<c.length;++e)a[e]=c.charCodeAt(e);c=a}R(this,16,1,48,[b,-1],{[115]:c});lc(this,b)}};function lc(a,b){if(b=a.j[b])b.m=null,b.v=null,b.Fa&&a.P(b)}
function oc(a,b){let c=a.i;if(b.B||a.o[b.tabId]||!c[-6])return 1;if(b.l)return 6;if(b.g&&c[-1])return 1;a=b.ua;let e=b.J=V(a.pathname);return c[9].test(a.hostname)||c[19].test(a.href)?1:(b.V&7)==2&&(b.O||c[-10])?a.pathname.endsWith("/")||c[21].test(a.pathname)?1:c[1].test(e)||!c[20].test(e)?4:1:6}
function pc(a,b){let c=!b.h;if(b.l&&c)return 3;a=a.i;var e=a[18];let d=a[1];var f=b.ua;let g=b.J,h=b.ka||(f.search?null:g),k=b.g,l=Ia.includes(b.type),m=!b.O;var p=!l&&e.exec(f.href);if(p){var q=e.$b,t=e.ac;let v=e.bc,z=e.cc;for(e=1;e<p.length;++e)if(p[e]){q=q[--e];if(q===null)break;var r=void 0;p=0;q.includes("G")&&(r=!0,p|=b.method=="GET");q.includes("P")&&(r=!0,p|=b.method=="POST");if(r&&!p)break;r=q.includes("V")|q.includes("A")|q.includes("C");q.includes("H")&&(b.U=!0);if((r?b.U:k?!q.includes("S"):
q.includes("X"))||m&&q.includes("D"))return 1;let x,C,G;if(p=z[e]){p=p.exec(f.href);if(!p)break;f=t[e];if(t=f.F)G=!0,C=p[t];if(t=f.T)G=!0,x=p[t]}x||=V(C)||q.includes("T")&&(G=!0,g)||v[e];if(r)return x&&(b.J=x),k||(b.g=!0),b.h=!0,6;if(c&&(x?d.test(x):!G))return b.aa=16777216,4;break}}return c?h&&(l&&a[2].test(h)||k&&a[4].test(h))?1:6:6}
function qc(a,b){if(b.ia)return W(a,6,b),6;var c=b.statusCode;if(c!=200&&c!=206&&c!=304)return 1;var e=Z(b.u,"Content-Type"),d=Z(b.u,"Content-Disposition"),f=rc(e).toLowerCase();let g=rc(d).toLowerCase()=="attachment";c=b.g;var h=b.C;if(b.ha=h&&!g&&f=="text/html"){if(b.j){var k=a.u[O(b.tabId,b.frameId)];k&&(k.j=!0);W(a,5,b)}return 1}if(c?b.B:b.h)return 1;if(a.va&&h&&g)return 4;let l,m,p,q,t,r;var v;let z;let x,C=a.i,G=b.port,P=b.ua;var ha=P.hostname;let qa=P.pathname,w=(d=sc(d,"filename")||sc(e,"name"))&&
V(d);if(d){if(!w&&!c)return 1;if(w&&(!c||w.length<=5)){var A=sc(e,"charset");x=!A||A=="utf-8"||A=="utf8";A=!0}}A||(d=qa.split("/").pop(),(w=b.J||V(d))&&w.toLowerCase()==f.split("/").pop()&&(A=!0));if(!A){e=C[10].test(f);var I=xa[f];I&&(I=I.split("|"),w&&I.includes(w)?A=!0:c&&Va(w)?A=!0:(c?e:w)||(A=!0,z=e,w=I[0]));!A&&w&&(g&&h?A=!0:e?A=z=!0:I||Ua(w)||(A=z=!0))}if(c){I=Gb(a,ha);h=a.X[I];e=qa+P.search;switch(I){case 0:break;case 1:if(h[111].test(e))l=A=!0,w=null;else if(h[112].test(e))m=!0;else if(h[115].test(e)&&
f=="application/json")r=!0;else if(h[113].test(e)||h[114].test(e))p=!0;break;case 2:(ha=h[111].exec(e))&&(Ta(f)||f=="text/html")?(f=ha[1]&&h[112].exec(G.G))&&ha[1]!=f[1]||(p=!0):h[114].test(e)?t=!0:g&&b.type=="image"&&w=="MP4"&&(v=!0);break;case 3:w=="M4S"&&(A=!0);ha==h[111]&&h[112].test(qa)&&Ta(f)&&(p=!0);break;case 4:h[111].test(e)&&Ta(f)&&(t=!0);break;case 5:h[111].test(e)&&f=="text/html"&&(t=!0);break;case 6:h[111].test(e)&&(p=!0);break;default:h[111].test(qa)&&(t=!0)}A&&(w=="M3U8"||w=="F4M"||
w=="MPD"?p=!0:w=="F4F"&&(d.endsWith("Seg1-Frag1")||d.endsWith("Seg1-Frag2")||d.includes("Seg1-Frag2_"))&&(q=!0));w=="ASF"&&((f=Z(b.u,"Content-Length"))&&parseInt(f)<=102400&&(v=!0),Z(b.u,"Server")=="DCLK-AdSvr"&&(v=!0))}if(v)return 1;A&&(c&&C[3].test(w)?l=!0:c&&C[4].test(w)?b.h=!0:!b.h&&C[1].test(w)&&(k=!0));if(l){let xb,yb;if(b.U)l=!1;else if(v=C[11])v.test(P.hostname)?l=!1:(xb=a.g[b.tabId])&&(yb=xb.G)&&v.test((new URL(yb)).hostname)&&(l=!1)}if(t||r)t&&G.O<0||r&&G.v<0?p=!0:m=b.ba=!0;if(p||q)!b.port||
b.method=="POST"&&!b.i?m=!1:(b.m=q?-1:1,m=!0);if(!k&&!l&&!m)return 1;A&&(b.ka=w);x&&(b.M=d);b.j|=m;b.aa=l||m?256:16|(c?4096:0)|(z?8388608:0);return k?4:l?2:5}
function W(a,b,c,e,d){var f=c.url,g=c.V||S(f);let h=c.requestHeaders,k=(g&7)==1;if(!e&&!h&&k)if(d===void 0){if(d=Z(h,"Cookie"),d==null)return T(f).then(x=>W(a,b,c,e,x||null))}else d=U(d);let l=e?e.id:c.id,m=c.port&&c.port.id,p=c.timeStamp,q=c.aa,t=c.u,r=c.X,v=c.A,z=0;(v?v.length-v.replaceAll(".","").length:0)==3?q|=33554432:(v?v.length-v.replaceAll(":","").length:0)>2&&(q|=4194304);g&16&&(q|=2097152);c.method=="POST"&&(q|=512);e&&(z|=129);c.j&&c.m&&(z|=1);c.j&&b!=5&&(z|=32);c.g&&(z|=16);c.H&&(z|=
8192);c.C&&(z|=c.D?2048:4096);g=[l,m,B(p),c.statusCode,g&7,b,c.tabId,c.frameId];f={[6]:Mb(f,k&&a.M),[12]:c.statusLine,[17]:c.da,[4]:c.ka,[100]:c.M,[127]:c.na,[129]:c.ja,[2]:c.A,[122]:a.D,[8]:q,[11]:tc(h),[13]:tc(t),[18]:tc(r)};c.i&&(f[14]=kc(c.i,h));c.I&&(f[19]=kc(c.I,r));h||(f[50]=uc(a,c),f[51]=d,f[54]=navigator.userAgent);if(!c.ha||!c.D)if(d=a.g[c.tabId])f[7]=d.G;return!!R(a,13,1,z,g,f)}
n.P=function(a,b,c){let e=this.j,d;if(E(a)||(a=e[a])){var f=a.id,g=a.statusCode>0;if(b){if(a.C||a.H)c=g||!a.requestHeaders,(g=this.u[O(a.tabId,a.frameId)])&&g.i&&a.D?browser.tabs.remove(a.tabId):c&&!a.H&&(d={redirectUrl:"javascript:void(0)"});d||={cancel:!0};a.N=!0}else c&&(d={[g?"responseHeaders":"requestHeaders"]:c});(c=a.resolve)&&b!==void 0&&(a.resolve=a.reject=null,c(d||{}));if(b=a.reject)a.resolve=a.reject=null,b();if(a.Ca||a.m||a.ba)return a.Fa=!0,d;delete e[f];a.v&&delete e[a.v];return d}};
n.ab=function(a){var b=a.type,c=a.tabId,e=a.frameId;if(!(c<0&&a.initiator==Pa)){var d=a.url,f=a.method,g=S(d);if(g&&(f=="GET"||f=="POST")&&d!=this.Ma){e&&a.frameType=="outermost_frame"&&(e=a.frameId=0);var h=a.id=a.requestId;h=this.j[h];var k=this.Ba,l=f=="POST",m=b=="image",p=b=="other",q=!p&&c<0&&e<0,t=c>0&&b.endsWith("_frame");if((f=q?null:this.g[O(c,e)])||t||q||p||h){t&&Db(this,a,null,!1);if(!k&&l&&a.requestBody){l=a.requestBody;var r=l.raw;if(r)for(let v=0;v<r.length&&(r[v].bytes||(r=null));v++);
if(!(r||l.formData||l.error))return}if((l=this.ya)&&(r=f?f.id==l&&f:this.m[l])&&d==r.H){p=r.I;if(l=r.J)a.M=l,a.ka=V(l);f||=r;this.ya=null}l=new URL(d);l.hash="";a.ua=l;a.V=g;a.l=this.pa;a.B=k;a.D=t&&b=="main_frame";a.C=t;a.H=p;a.ga=q;a.g=q||Ja.includes(b);a.h=m;a.j=this.Oa.test(d);a.i=a.requestBody;a.port=f;a.O=g&8||this.ra[g];c<0&&(a.tabId=null);e<0&&(a.frameId=null);h&&(a.id=h.id,a.port=f=h.port,a.l=h.l,a.B=h.B,a.da=h.da||h.url,a.X=h.X||h.requestHeaders,a.I=h.I||h.i);if(a.g&&!m){b=this.ba;c=b.Sb;
e=c.indexOf(d);if(e>=0)c.splice(e,1);else for(;c.length>=30;)delete b[c.shift()];b[d]=f;c.push(d)}switch(a.action=oc(this,a)){case 1:a.h=!0;case 6:d=this.j;f=a.id;d[f]!==a&&(d[f]=a);break;case 4:a.o=!0}}}}};
n.Ib=function(a){let b=this.j[a.requestId],c;if(b){let d=b.requestHeaders=a.requestHeaders;b.timeStamp=a.timeStamp;if(!b.N){if(b.ga&&!b.port&&(a=Z(d,"Referer")))for(var e of u(this.m))if(e.G==a){b.port=e;break}if(b.port&&b.type=="xmlhttprequest"){let f,g;e=0;for(f of d)if(f.name.toLowerCase()=="accept"&&(g=Ya(f.value)))break;else e++;if(g){a=g[3];let h=g[4];c=!1;g[1]||g[5]?f.value=g[1]+(g[5]&&g[2]||"")+g[5]:d.splice(e--,1);if(a=="pxr"||a=="pfm")b.v=h,this.j[h]=b;else if(a=="int")return this.P(b,!1,
c&&d)}}if(b.method=="POST"&&(!b.i||b.i.error&&Z(d,"Content-Length")>0))return this.P(b);switch(b.action=pc(this,b)){case 1:b.h=!0;break;case 4:b.o=!0;return;case 3:b.o=!0;return}if(c)return{requestHeaders:d}}}};
n.Lb=function(a){let b=this.j[a.requestId];if(b){var c=b.port,e=b.type,d=b.statusLine=a.statusLine,f=b.statusCode=a.statusCode||parseInt(d.split(" ",2).pop()),g=a.responseHeaders;if(b.N||f==204&&d.includes(" IDM "))return this.P(b,!0);b.A=a.ip;b.$=a.timeStamp;b.ja=B(a.timeStamp-b.timeStamp);b.u=g;b.ia=ab(f);if(e=="image"&&(a=Z(g,"Content-Type"))&&a.toLowerCase().startsWith("image"))return this.P(b);Z(g,"Client-Protocol")=="quic"?b.V|=16:(a=Z(g,"Alternate-Protocol"))&&a.endsWith(":quic,p=0")&&Z(g,
"Transfer-Encoding")!="chunked"&&(b.V|=16);if(c&&e=="xmlhttprequest"&&!b.v&&c.v==2){e=oa.map(Z.bind(J,g));e.unshift(b.url);e=e.join("|");g=5381;a=e.length;for(d=0;d<a;d++)g=g*33+e.charCodeAt(d)>>>0;c=b.v=`${c.id}-${g}`;this.j[c]=b}switch(b.action=qc(this,b)){case 1:return!1;case 4:b.o=!0;break;case 3:b.o=!0}}};
n.Mb=function(a){let b=this.j[a.requestId];if(a.type.endsWith("_frame")&&(a.statusCode==200||a.statusCode==304)){let c=this.u[O(a.tabId,a.frameId)];c&&(c.G=a.url,c.da=c.v)}b&&(b.A||(b.A=a.ip),b.action==2?W(this,4,b):b.action==5&&W(this,5,b))};n.Jb=function(a){(a=this.j[a.requestId])&&(!a.o||a.Ca?this.P(a):J.setTimeout(this.P,250,a))};n.Kb=function(a){this.P(a.requestId)};
async function nb(a){var b={url:K.homepage_url},c=browser.storage.local.get(null);b=browser.cookies.getAll(b);let e=browser.extension.isAllowedIncognitoAccess();[c,b,e]=await Promise.all([c,b,e]);a.Ta=c.version;a.ia=c.silent;a.I=c.lastupt;a.Na=e;a.I>Date.now()&&(a.I=null);c=c.client;let d;if(b)for(let f of b)switch(f.name){case "idmwebext_cid":d=parseInt(f.value)}cc(a,null,c,d);a.Aa()}
function cc(a,b,c,e){(b||=c||e)&&b!=a.$&&(a.$=b,c||browser.storage.local.set({client:b}),e||browser.cookies.set({url:K.homepage_url,name:"idmwebext_cid",value:String(b),expirationDate:2147483647}))}
function Ib(a){a.R&&(browser.tabs.remove(a.R),a.R=null);if(a.Ua){var b=!a.B,c=!a.Na,e=a.M,d=a.qa,f=a.Ta,g=a.Qb;if(b){if(a.ha&&a.ia)return}else a.Ua=!1,g!=f&&g&&browser.storage.local.set({version:g}),a.ia&&(a.ia=!1,browser.storage.local.set({silent:!1}));f!=null&&(g==f||d&&f&&!e)||(g=Oa+"current="+escape(g),f&&(g+="&previous="+escape(f)),d&&(g+="&manager="+(d?[d>>24&255,d>>16&255,d>>8&255,d&255].join("."):"")),b&&(g+="&error=1"),c&&(g+="&incognito=1"),e&&(g+="&update=1"),aa&&(g+="&opera=1"),browser.tabs.create({url:g},
function(h){h&&(this.R=h.id)}.bind(a)))}}function dc(a,b,c){b==null&&(b=$a(c[13]))&&(b=b[1]<<24|b[2]<<16|b[3]<<8);a.qa=b>>>0}function ec(a){a.M=a.qa<103418624;a.qa<103424E3?a.H=a.I?a.I+B(D()*240+480)*6E4:Date.now():(a.H=a.I=null,browser.storage.local.remove("lastupt"))}function Pb(a,b){var c=Date.now();if(c>a.H||b&&!a.M)browser.storage.local.set({lastupt:a.I=c}),a.H>0&&(a.H=c+B(D()*240+480)*6E4),c="idmdwnlmfv4://idmreg://"+D().toString(36).substr(2),b?a.ma(c):J.setTimeout(a.ma,B(D()*5E3+5E3),c)}
function uc(a,b){a=a.u;b=O(b.tabId,b.frameId);var c;do b=(c=a[b])&&c.h,c=c&&c.G,c=="about:blank"&&(c=null);while(!c&&b);return c}function Ob(a,b){b=browser.i18n.getMessage(b);browser.scripting.executeScript({target:{tabId:a},func:function(c){window.alert(c)},args:[b]},Hb)}n.L=function(a,b,c){if(b!=null){var e=fa(arguments);this.Ja.push(e);b.addListener.apply(b,e.slice(2))}};
n.Ka=function(){let a=arguments.length?fa(arguments):null,b=this.Ja;for(let c=0;c<b.length;c++){if(a&&!a.includes(b[c][0]))continue;let e=b.splice(c--,1).pop(),d=e.splice(0,2).pop();d.removeListener.apply(d,e)}};function hc(a){return browser.i18n.getMessage(a)||a}function Mb(a,b){let c=a.lastIndexOf("#");c>a.indexOf("?")&&a[c+1]!="!"&&(a=a.substr(0,c));!b||a.startsWith("idmdwnlmfv")||Wa(a)||(a=`${"idmdwnlmfv"}4://${a}`);return a}
function S(a,b){a=a.split(":",1).shift().toLowerCase();a=ua[a]||0;return b?a&7:a}function V(a){return(a=Za(a))?a[1].toUpperCase():""}function T(a,b){a={url:a};b&&(a.session=!1);return browser.cookies.getAll(a).catch(()=>null)}function U(a){if(!E(a))return a;let b=[];for(let c of a)b.length&&b.push("; "),b.push(c.name,"=",c.value);return b.join("")}
function tc(a){if(!a||!a.length)return null;let b=[];for(let c of a)b.push(c.name,": "),c.value!=null?b.push(c.value):c.binaryValue&&b.push(new Uint8Array(c.binaryValue)),b.push("\r\n");return b}function Z(a,b){if(!a)return null;b=b.toLowerCase();for(let c of a)if(c.name.toLowerCase()==b){if(c.value!=null)return c.value;if(c.binaryValue)return F(c.binaryValue)}return null}
function sc(a,b){if(!a)return null;let c,e;a=a.split(";");for(b=b.toLowerCase();a.length;){var d=a.shift();let g=d.indexOf("=");if(g>0){var f=d.slice(0,g).trim().toLowerCase();let h=f.endsWith("*");if(h)f=f.slice(0,-1).trimRight();else if(e)continue;if(f==b){f=d.substr(g+1).trim();d=f.length-1;if(f[0]=='"'?f[d]=='"':f[0]=="'"&&f[d]=="'")f=f.slice(1,d);if(h&&f.includes("'")){if(f=f.split("'",3),h=f.shift().toLowerCase(),f=f.pop(),((d=h=="utf-8"||h=="utf8")||!e)&&(c=vc(f))&&(e=h,d))break}else c=vc(f)}}else g<
0&&c==null&&d.trim().toLowerCase()==b&&(c="")}return c}function rc(a){const b=/[;,]/;return(a&&=a.split(b,1).shift().trim())&&!a.includes("=")&&vc(a)||""}function vc(a){try{return a&&decodeURIComponent(a)}catch(b){return unescape(a)}}
function kc(a,b,c){let e;var d;let f=[];if(e=a.raw)for(d of e){var g=d.bytes;if(g)f.push(c?F(new Uint8Array(g)):g);else return null}else if(d=a.formData)if(b=ea(b)?Z(b,"Content-Type"):b,(a=rc(b).toLowerCase())&&a!="application/x-www-form-urlencoded")if(a=="multipart/form-data"){var h=sc(b,"boundary");h||="----WebKitFormBoundary"+D().toString(36).substr(2);for(g in d)for(let k of d[g])c&&k instanceof ArrayBuffer&&(k=F(new Uint8Array(k))),f.push("--",h,'\r\nContent-Disposition: form-data; name="',g,
'"\r\n\r\n',k??"","\r\n");f.push("--",h,"--\r\n")}else return null;else for(h in d){g=encodeURIComponent(h).replaceAll("%20","+");for(let k of d[h])k=k instanceof ArrayBuffer?escape(F(new Uint8Array(k))):k==null?"":encodeURIComponent(k),f.length&&f.push("&"),f.push(g,"=",k&&k.replaceAll("%20","+"))}else return null;c&&(f=f.join(""));return f.length?f:null}function fb(a){let b=a.length,c=b,e=0;for(;e<c;){let d=a.charCodeAt(e++);d>=128&&(d>=2048?(b+=2,d-55296&64512||e++):b++)}return b}
function Bb(a,b){a=a.replace(/^\|+|\|+(?=\||$)/g,"").replace(/\./g,"\\.");a=b==1?a.replace(/\?/g,"[^/\\\\]").replace(/(^|[^*])\*(?!\*)/g,"$1[^/\\\\]*").replace(/\*\*/g,".*?"):b==3?a.replace(/(?<![*?])\*(?!\*)/g,"[^/]*").replace(/\?\*/g,"\\?.*").replace(/\*\*/g,".*?"):a.replace(/\?/g,".").replace(/\*/g,".*?");b==2&&(a=a.replace(/(^|\|)([^|]+?)~/g,"$1(?:$2\\.)?").replace(/(^|\|)~/g,"$1(?:.*?\\.)?"));return"^(?:"+a+")$"}
function Y(a,b,c,e){if(b=b[c]||void 0){b=Bb(b,e);try{b=RegExp(b,e==1?"":"i")}catch(d){b=null}}a[c]=b||Ga}
function fc(a,b,c,e,d){b=b[c];let f=[],g=[],h=[],k=[];if(b)try{b=b.replace(/^\|+|\|+(?=\||$)|\*+(?=\*)/g,"").replace(/[.?+(){}[\]]/g,"\\$&").replace(/\*(?=[^:/|&]*:\/\/)/g,"\\w%%").replace(/(:\/\/[^:/]*?)~/g,"$1(?:\\b[^./]+\\.)?").replace(/\\\?(?=\||$)/g,"(?:$&.%%)?");if(e){for(var l=b.replace(/(^|\|)(?:([A-Z]+)?(?:#(\w+))?!)?[^|]+/g,"$1$2|$3").split("|");l.length;){var m=l.shift();f.push(Xa(m)?m:null);g.push(l.shift())}b=b.replace(/(^|\|)[\w#]+!/g,"$1")}if(d){let p=b.replace(/(^|\|)(?:(?=[^|]+?<[A-Z]:.*?>)|[^|]+)/g,
"$1").split("|");l=/<([A-Z]):(.*?)>/g;m={F:"[^/\\?#&;]%%",T:"[^/\\?#&;.]%%"};for(let q,t=0;p.length;++t)if(q=p.shift()){let r={},v=["^"],z="";for(let x,C=1;x=l.exec(q);++C)r[x[1]]=C++,z=RegExp.rightContext,v.push(RegExp.leftContext,"(",x[2].replace(/\*/g,m[x[1]]||".%%?"),")");v.push(z,"$");h[t]=r;k[t]=RegExp(v.join("").replace(/\*/g,".*?").replace(/%%/g,"*"))}b=b.replace(l,"(?:$2)")}b=b.replace(/\*/g,".*?").replace(/%%/g,"*");b=e||d?RegExp("^(?:("+b.replace(/\|/g,")|(")+"))$"):RegExp("^(?:"+b+")$")}catch(p){b=
null}a[c]=b||=RegExp("(?!)");e&&(b.$b=f,b.bc=g);d&&(b.ac=h,b.cc=k)}function bc(a){return browser.runtime.lastError?null:browser.permissions.request({permissions:[a]})}function Hb(a){browser.runtime.lastError;a;!0}
const pb=[null,[!0,-8,"menu_download_link","link,image,video",Q.prototype.Da],[!0,-8,"menu_download_link","page,frame,editable",Q.prototype.Da,Ma],[!0,-8,"menu_download_selected","selection",Q.prototype.La],[!0,-9,"menu_download_all","page,frame,editable",Q.prototype.La],[!0,-8,"menu_download_item","link",Q.prototype.Da,["chrome://downloads/*"]]],tb=hc("tooltip_title"),vb=hc("tooltip_disabled"),wb=hc("tooltip_error"),ub="\n"+hc("tooltip_text");
(async function(){var a=browser.runtime.getPlatformInfo(),b;navigator.userAgentData&&(b=navigator.userAgentData.getHighEntropyValues(["fullVersionList","uaFullVersion"]));var c=browser.management.get("clhiejnehegdfknplplojohghjaklbae").catch(()=>null);[a,b,f,c]=await Promise.all([a,b,f,c]);if(a&&a.os!="win")return sb(!1);a=navigator.userAgent;var e=a.match(/\s(?!(?:Chrome|Firefox|Gecko|Safari)\/)([A-Z]\w+)(?:\/(\d+(?:\.\d+){0,3}))?\b(?!.*\)\s+\S)/),d=a.match(/\s(Chrome|Firefox)\/(\d+(?:\.\d+){0,3})\b/);
a=d?d[1]:"UNKNOWN";var f=e?e[1]:a;d=d&&d[2]||"0.0";e=e&&e[2]||d;navigator.brave&&(f="Brave");c&&(f="Epic",Aa=!0);if(E(b)){if(c=b.uaFullVersion)e=c;if(b=b.fullVersionList)for(let g of b)if(c=g.version)switch(g.brand){case "Chromium":a="Chrome";parseInt(c)==parseInt(d)?d=c:(f="UNKNOWN",e=c);break;case f:e=c}}c=d.split(/\D+/);ya=`${a}/${d}`;za=`${f}/${e}`;new Q})();
